### ISSUE TITLE
Rename "Webex Teams" to "Cisco Webex Teams"

### ISSUE THREAD

**Issue by theycallmeswift** [howdyai/botkit-docs#16]
Hey, folks!

We've been experimenting with Botkit for some tutorials and have been observing a small UX bug that leads to user error.  Let me know if you have questions or concerns.

**Problem**:
The sidebar in the documentation says "Webex Teams" under platforms.  This is confusing because the official name of the product is "Cisco Webex Teams" and most people colloquially refer to the product as "Cisco Webex", not "Webex Teams".  Additionally, there's a high probability of user error because "Cisco Jabber" appears directly below "Webex Teams" in the list and on a quick scan you could easily click the wrong link if you were scanning for the word Cisco.

**Proposed Solution**:
Update the name of the sidebar link to "Cisco Webex Teams" from "Webex Teams".

**Comment by theycallmeswift** [comment]
It may also be prudent to update the Cisco Spark logo on your homepage to the Cisco Webex Teams logo.

![sponsor-cisco-webex-logo-indigo](https://user-images.githubusercontent.com/434373/45843720-59d26880-bcee-11e8-9385-228e4d0d5254.png)

**Comment by peterswimm** [comment]
If anyone wants to make these changes as a pr we will review. The biggest hurdle in changing them is breaking links throughout the docs for named pages, so once that is resolved we can push the changes as a total.
