### ISSUE TITLE
Broken storage_test.js link

### ISSUE THREAD

**Issue by jbankes** [howdyai/botkit-docs#23]
On the [Storing Information Doc](https://botkit.ai/docs/storage.html) there is a broken link pointing to a javascript file the doesn't exist. [storage_test.js](https://github.com/howdyai/botkit/blob/master/lib/storage/storage_test.js) is the link in problem. Is the link somewhere else or should this be removed?

**Comment by ouadie-lahdioui** [comment]
Nice catch!
