### ISSUE TITLE
Update Wordhop to Janis

### ISSUE THREAD

**Issue by joshbarkin** [howdyai/botkit-docs#8]
Wordhop re-branded as Janis.ai over a year ago. 
Please update the Repo link to https://github.com/Janis-ai/npm-janis
Also Botkit plugin name is:  Janis.ai
Plugin description:  
Janis is an AI management toolkit that enables teams working in Slack to collaborate on AI training, monitor bots for problems, and quickly resolve and prevent business-impacting incidents. 

<img width="985" alt="screen shot 2018-06-24 at 1 43 25 am" src="https://user-images.githubusercontent.com/7429980/41816326-55240854-7750-11e8-87eb-7fbff2927bea.png">

**Comment by peterswimm** [comment]
@joshbarkin can you submit a PR with the changes?

**Comment by benbrown** [comment]
@joshbarkin this has (Finally) been updated1

**Comment by joshbarkin** [comment]
Thank you !

Thanks,

- josh
